name: Node.js CI
on:
  push:
    brandches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: git clone https://github.com/monyratha/express-api.git
      - name: List folders
        run: ls