name: Node.js CI
on:
  push:
    brandches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Action repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Test Node Version
        run: node -v
      - name: check current working directory
        run: pwd