name: Node.js CI
on:
  push:
    brandches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test VM
        run: ls -la